version: '3.8'

services:
  cv_scanner_db:
    image: postgres:15
    container_name: cv_scanner_db
    environment:
      POSTGRES_USER: cv_user
      POSTGRES_PASSWORD: cv_password
      POSTGRES_DB: cv_scanner_db
    ports:
      - "5434:5432"   
    volumes:
      - postgres_cv_data:/var/lib/postgresql/data

volumes:
  postgres_cv_data: