spring.application.name=cv-scanner

spring.datasource.url=jdbc:postgresql://localhost:5434/cv_scanner_db
spring.datasource.username=cv_user
spring.datasource.password=cv_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.jdbc.initialize-schema=always

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

springdoc.swagger-ui.path=/swagger-ui.html

# Spring Mail 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=testpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.batch.job.enabled=false